### ISSUE TITLE
Needs more docs

### ISSUE THREAD

**Issue by drcrallen** [metamx/druid-spark-batch#4]
Before any public release, this needs more documentation.

**Comment by l15k4** [comment]
Hey, could you please include some Rationale of this extension? Like what is the reason of its existence, what problems does it solve, etc.

**Comment by xvrl** [comment]
@l15k4 we moved all our internal batch processing from Hadoop to Spark, so we also wanted Druid indexing run on Spark to avoid maintaining a separate Hadoop cluster just for Druid

**Comment by zzl0** [comment]
@drcrallen I am new to Java(JVM) world, I have deployed Druid in a test environment, and the query performance is good, but the local batch indexer is slow, so I want to use Spark-batch indexer to improve the batch indexing task. 

1. I download the `druid-spark-batch` project.
2. And issued command `sbt clean test publish-local publish-m2`.

Then is got the following error:

```
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.apache.spark#spark-core_2.10;1.5.2-mmx4: not found
[warn] 	:: io.druid#druid-processing;0.9.1-SNAPSHOT: not found
[warn] 	:: io.druid#druid-server;0.9.1-SNAPSHOT: not found
[warn] 	:: io.druid#druid-indexing-service;0.9.1-SNAPSHOT: not found
[warn] 	:: io.druid#druid-indexing-hadoop;0.9.1-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
.
.
.
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.spark#spark-core_2.10;1.5.2-mmx4: not found
[error] unresolved dependency: io.druid#druid-processing;0.9.1-SNAPSHOT: not found
[error] unresolved dependency: io.druid#druid-server;0.9.1-SNAPSHOT: not found
[error] unresolved dependency: io.druid#druid-indexing-service;0.9.1-SNAPSHOT: not found
[error] unresolved dependency: io.druid#druid-indexing-hadoop;0.9.1-SNAPSHOT: not found
[error] Total time: 79 s, completed May 11, 2016 11:07:41 AM
```
