### ISSUE TITLE
org.apache.spark#spark-core_2.10;1.5.2-mmx4: not found

### ISSUE THREAD

**Issue by zzl0** [metamx/druid-spark-batch#66]
## What's the problem?

I am trying to use  `druid-spark-batch`, and got the following error:
```
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.apache.spark#spark-core_2.10;1.5.2-mmx4: not found
[warn] 	:: io.druid#druid-processing;0.9.1-SNAPSHOT: not found
[warn] 	:: io.druid#druid-server;0.9.1-SNAPSHOT: not found
[warn] 	:: io.druid#druid-indexing-service;0.9.1-SNAPSHOT: not found
[warn] 	:: io.druid#druid-indexing-hadoop;0.9.1-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
.
.
.
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.spark#spark-core_2.10;1.5.2-mmx4: not found
[error] unresolved dependency: io.druid#druid-processing;0.9.1-SNAPSHOT: not found
[error] unresolved dependency: io.druid#druid-server;0.9.1-SNAPSHOT: not found
[error] unresolved dependency: io.druid#druid-indexing-service;0.9.1-SNAPSHOT: not found
[error] unresolved dependency: io.druid#druid-indexing-hadoop;0.9.1-SNAPSHOT: not found
[error] Total time: 79 s, completed May 11, 2016 11:07:41 AM
```

## How to reproduce the isuue?

1. I download the druid-spark-batch project.
2. And issued command sbt clean test publish-local publish-m2.

**Comment by drcrallen** [comment]
We aren't running 1.6.1 internally yet, which is why the version is set to one we do run internally. The 1.5.1-mmx4 version has my patches to get this working correctly.

**Comment by drcrallen** [comment]
Solution is to change the version at https://github.com/metamx/druid-spark-batch/blob/v0.9.1-0/build.sbt#L35

Note that this extension is still very sensitive to which druid version it is compiled against, so there are branches for different druid releases

**Comment by zzl0** [comment]
Thanks for your reply.

**Comment by richiesgr** [comment]
Hi
it still not working I can't find anywhere the version 1.5.2-mmx4
it's not in maven central
